sudo: true
dist: trusty

language: node_js

node_js:
  - "6"

os:
  - osx
  - linux

before_install:
  - git clean -xdff
  - npm i -g yarn@latest
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

env:
  - GOPATH=$TRAVIS_BUILD_DIR/test/server

install:
  - yarn

before_script:
  - node test/server/lfs-server.js

script:
  - $TRAVIS_BUILD_DIR/test/server/run.sh & yarn test