sudo: true
dist: trusty

language: node_js

node_js:
  - "6"

os:
  - osx
  - linux

addons:
  addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - libxkbfile-dev
    - libxss-dev

before_install:
  - git clean -xdff
  - npm i -g yarn@0.24.5
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

env:
  - GOPATH=$TRAVIS_BUILD_DIR/test/server CC=clang CXX=clang++ npm_config_clang=1

before_install:
  - cd .. && git clone -b fix/asyncify_methods https://github.com/cjhoward92/nodegit.git
  - cd nodegit && npm i && yarn link && cd ../nodegit-lfs
  - yarn link nodegit

install:
  - yarn

script:
  - yarn test